services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bytebattles-rabbitmq
    ports:
      - "50301:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - bytebattles-network

  codeexecution:
    build:
      context: .
      dockerfile: ByteBattlesServer.Microservices/ByteBattlesServer.Microservices.CodeExecution/ByteBattlesServer.Microservices.CodeExecution.API/Dockerfile
    container_name: bytebattles-codeexecution
    ports:
      - "5277:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=bytebattles_tasks;Username=postgres;Password=1;Port=5432
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - bytebattles-network

  taskservices:
    build:
      context: .
      dockerfile: ByteBattlesServer.Microservices/ByteBattlesServer.Microservices.TaskServices/ByteBattlesServer.Microservices.TaskServices.API/Dockerfile
    container_name: bytebattles-taskservices
    ports:
      - "5278:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=task_service;Username=postgres;Password=1;Port=5432
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - bytebattles-network

  postgres:
    image: postgres:15
    container_name: bytebattles-postgres
    environment:
      - POSTGRES_DB=bytebattles_tasks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bytebattles-network

networks:
  bytebattles-network:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data: