# docker-compose.yml

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bytebattles-rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  auth-service:
    build:
      context: .
      dockerfile: ByteBattlesServer.Microservices/ByteBattlesServer.Microservices.AuthService.API/Dockerfile
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
    depends_on:
      - rabbitmq

  userprofile-service:
    build:
      context: .
      dockerfile: ByteBattlesServer.Microservices/ByteBattlesServer.Microservices.UserProfile.API/Dockerfile
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data: